{% set name = "google-cloud-dataform" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-dataform-{{ version }}.tar.gz
  sha256: bda88e26edbc7ba219bbc5a8484f62914a24784429e427d60fe8d427732e9c35

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - google-api-core >=2.8.0,<3.0.0dev
    - grpc-google-iam-v1 >=0.12.4,<1.0.0dev
    - proto-plus >=1.22.0,<2.0.0dev
    - protobuf >=3.19.0,<5.0.0dev

test:
  imports:
    - google
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-dataform
  summary: Cloud Dataform API client library
  license: Apache-2.0
  license_file:
    - LICENSE
  license_family: Apache
  dev_url: https://github.com/googleapis/python-dataform

extra:
  recipe-maintainers:
    - xylar
